sudo: required
dist: bionic
language: go
go:
  - 1.16.x
  - 1.17.x

go_import_path: github.com/rh-messaging/shipshape

services:
  - docker

git:
  depth: 1

env:
  global:
    - KUBECONFIG=$HOME/.kube/config
    - KUBERNETES_VERSION=$(curl -k -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

before_install:
  # Setup kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

  # Get tools
  - git clone https://github.com/skupperproject/skupper-cli.git && cd skupper-cli && make build && cp skupper $GOPATH/bin
  - go get sigs.k8s.io/kind@latest
  - go get github.com/jfeliu007/goplantuml/parser@latest
  - go get github.com/jfeliu007/goplantuml/cmd/goplantuml@latest
  - cd -

  # Create a new Kubernetes cluster using KinD
  - kind create cluster
  - kubectl cluster-info

script:
  - cd $GOPATH/src/github.com/rh-messaging/shipshape
  - make uml
  - env make
  - env make unit-tests
  - env make cluster-test

